### ISSUE TITLE
Issues with encoding segments and ignored prefixes

### ISSUE THREAD

**Issue by chaplja** [zyantific/zydis#118]
Hi,

I've been testing the latest master branch and have found a few issues with the new encoding segment information and prefixes marked as ZYDIS_PREFIX_TYPE_IGNORED. There are duplicates as some instructions differ only in operand values (e.g. different registers) and there may be duplicates due to different architecture used, but are left anyway (e.g. same issue appears when decoding instruction in 32-bit and 64-bit mode).

List of potential issues can be found [here](https://gist.github.com/chaplja/18edd349bd1ffa1634386a3c3f9fa8f2).

There are a few checks that have been performed:

###  Enumerating all segments using ZydisGetInstructionSegments
 - verifying that the next segment starts at the sum of sizes of all previous segments
 - verifying that the sum of sizes of all segments equals size of the instruction (this is actually not visible in the linked report because it fails on the first check)

Example:
`[intel32] SEGMENT_DATA_MISMATCH: [0f 0f c0 96] (pfrcp mm0, mm0) segment #1 expected at offset 3, found at 2`

> ZydisInfo.exe -32 0f 0f c0 96

Notice C0 being displayed twice while byte 96 is not listed.

### Enumerating all prefixes and testing ignored ones.
 - enumerating all prefixes and assembling blob of data without prefixes marked as ZYDIS_PREFIX_TYPE_IGNORED, which is then decoded again. It should produce identical instruction, otherwise prefixes are not really ignored.

Example:
`[intel64] MNEMONIC_DIFF: [66 36 af] vs [af] (scasw vs scasd)`

>ZydisInfo.exe -64 66 36 af [scasw]

Instruction is decoded as scasw. First two bytes (66 36) are marked as ZYDIS_PREFIX_TYPE_IGNORED. Eliminating them produces scasd, which is clearly a different instruction and the prefix 66 is not actually ignored.

>ZydisInfo.exe -64 af [scasd]

Another example:
`[intel32] OPERAND_DIFF: [67 aa] vs [aa] (stosb vs stosb)`

>ATTRIBUTES: CPUFLAG_ACCESS ACCEPTS_REP ACCEPTS_REPNE ACCEPTS_REPNZ HAS_ADDRESSSIZE

Prefix is marked as ignored, however it has effect on hidden operands:
>67 aa: stosb es:[di]
>aa: stosb es:[edi]

**Comment by flobernd** [comment]
Thanks for reporting, that indeed looks like a bug. I'll have a look at it!

**Comment by flobernd** [comment]
The first part of this issue should be fixed now. I forgot to take care of the special `3DNOW` encoding in the `ZydisGetInstructionSegments` function.

Having a look at the `ZYDIS_PREFIX_TYPE_IGNORED` problem now.

**Comment by chaplja** [comment]
Thanks. Can confirm it does appear to be fixed. I've made a large test once again and no segment inconsistencies have popped up.

**Comment by flobernd** [comment]
The second issue (incorrect `ZYDIS_PREFIX_TYPE_IGNORED` for some instructions with `0x66` prefix) should now be fixed.

As for the `0x67` prefixes the value was meant to be `ZYDIS_PREFIX_TYPE_EFFECTIVE` in all cases. I'm not sure if I can correctly determine the type for address-size-overrides at runtime. Well .. at least not efficiently. We might need a new flag in the data-tables (could improve performance for `0x66` as well).

Your `[67 aa]` example triggered a bug which changed the type to `ZYDIS_PREFIX_TYPE_IGNORED` for this special instruction (and a few more). This should be fixed now as well.

**Comment by chaplja** [comment]
Excellent, thanks! Made another test, found nothing unusual - I'm going to close the issue then. Keep up the great work!

**Comment by flobernd** [comment]
Thank you as well for testing and reporting this issue. Always appreciated!

**Comment by chaplja** [comment]
It seems like I missed something when re-doing the test. Instructions BSR and BSF still have issues with 0x66 prefix. Examples available at: https://gist.github.com/chaplja/72a3efd95724039d9cb4646fde8f3b36

**Comment by flobernd** [comment]
Thanks for reporting, I'll have a look. Might be related to #119.

**Comment by flobernd** [comment]
This was another edge-case which should be fixed now.

**Comment by chaplja** [comment]
Thanks! I've fixed the test in the meantime and everything I'm treating as a fatal error so far has been fixed.
